[slack]
[slack.test]
Token="xoxb-2037215048336-2021683593251-MTjUk35TY6recJ18Y53vWsbz"
PrefixMessagesWithNick=true

[discord]
[discord.test]
Token="ODM3ODkyMzQ2ODcxNTQ1ODU2.YIzKDg.lxGetOSOhPHSZL0FqnQrK4EWVGo"
Server="806425390343389194"

[general]
RemoteNickFormat="[{PROTOCOL}/{BRIDGE}] <{NICK}> "

[[gateway]]
    name = "mygateway"
    enable=true

    [[gateway.inout]]
    account = "discord.test"
    channel="status-updates"

    [[gateway.inout]]
    account ="slack.test"
    channel = "na"
